language: lisp
sudo: required
env:
  matrix:
    - LISP=sbcl
    - LISP=ccl
    - LISP=clisp

matrix:
  allow_failures:

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
script:
  - cd t
  - cl -e "(ql:quickload :prove)"  -e "(unless (prove:run :zenekindarl-test) (uiop:quit 1))"