language: lisp
env:
  matrix:
    - LISP=sbcl

matrix:
  allow_failures:

install:
  - curl -L https://github.com/luismbo/cl-travis/raw/master/install.sh | sh
script:
  - cl -C KeenS/arrows/t/ -e "(ql:quickload :prove)"  -e "(unless (prove:run :arrows-test) (uiop:quit 1))"